In [140]:
import matplotlib.pyplot as pp
import torch
import torchquad as tq
simp = tq.Simpson()

def parametrized_integrand(x, a, b):
    return torch.sqrt(torch.cos(torch.sin((a + b) * x)))


a_params = torch.arange(400)
b_params = torch.arange(10, 200)

import datetime
starttime = datetime.datetime.now()
integration_domain = torch.Tensor([[0, 1]])
simp = tq.Simpson()
result = torch.stack([torch.Tensor([simp.integrate(lambda x: parametrized_integrand(x, a, b), dim=1, N=101, integration_domain=integration_domain) for a in a_params]) for b in b_params])
endtime = datetime.datetime.now()
print(endtime - starttime)

0:00:09.340971


In [22]:
import datetime
starttime = datetime.datetime.now()
integration_domain = torch.Tensor([[0, 1]])
simp = tq.Simpson()
result = torch.stack([torch.Tensor([simp.integrate(lambda x: parametrized_integrand(x, a, b), dim=1, N=101, integration_domain=integration_domain) for a in a_params]) for b in b_params])
endtime = datetime.datetime.now()
print(endtime - starttime)

0:00:00.078783


In [225]:
import datetime
starttime = datetime.datetime.now()
grid = torch.Tensor([a for a in a_params])

t0 = torch.tensor([1,2,3])
t_scale = torch.randn([3])
tau = torch.randn([3,5])
def integrand(t):
    y = t*t_scale+t0
    ones = torch.ones(5)
    if len(y.shape) == 1:
        y = y.reshape(1,-1)
    tau_rep = tau.repeat(y.shape[0], 1, 1)
    tau_rep = tau_rep.view(y.shape[0], tau.shape[0], tau.shape[1])
    diff = (y.unsqueeze(2) - tau_rep)**2
    return diff

integration_domain = [[0, 2]]
result_vectorized = simp.integrate(integrand, dim=1, N=1001, integration_domain=integration_domain)
endtime = datetime.datetime.now()
print(endtime - starttime)

#torch.all(torch.isclose(result_vectorized, result)) # True!

0:00:00.006554


In [226]:
print(result_vectorized)

tensor([[ 1.5252,  2.0730,  6.9124,  0.2196,  2.8289],
        [29.0403, 16.0388, 35.1022,  0.7679, 23.0190],
        [57.2684, 50.2401, 52.0854, 30.5624, 36.9342]])


In [216]:
y = t_scale+t0
ones = torch.ones(5)
print(y.shape)
#result = torch.einsum('i,j->ij', y, ones)
def multi_tau(tt,tau):
    return tau - tt.unsqueeze(0)
if len(y.shape) == 1:
    y = y.reshape(1,-1)
tau_rep = tau.repeat(y.shape[0], 1, 1)
tau_rep = tau_rep.view(y.shape[0], tau.shape[0], tau.shape[1])
print(tau_rep.shape)
diff = tau_rep - y.unsqueeze(2)

torch.Size([3])
torch.Size([1, 3, 5])


In [218]:
y.unsqueeze(2).shape

torch.Size([1, 3, 1])

In [212]:
a = torch.rand((3, 4))
b = torch.rand((1, 4))

# repeat tensor a p times along a new dimension and reshape it to have shape (p, m, n)
a_rep = a.repeat(b.shape[0], 1, 1)
a_rep = a_rep.view(b.shape[0], a.shape[0], a.shape[1])

# subtract each row of b from a_rep
diff = a_rep - b.unsqueeze(1)

print(a_rep.shape)

torch.Size([1, 3, 4])


In [179]:
y = t_scale
ones = torch.ones(tau.shape[1])
torch.einsum('i,j->ij', y, ones)

tensor([[-0.1405, -0.1405, -0.1405, -0.1405, -0.1405],
        [ 1.0997,  1.0997,  1.0997,  1.0997,  1.0997],
        [ 0.2802,  0.2802,  0.2802,  0.2802,  0.2802]])

In [184]:
result_vectorized

tensor([-8.2278e-04,  1.9964e+00,  8.7565e+00])

In [175]:
ones = torch.ones(len(t_scale))
torch.einsum('i,j->ij', t_scale, ones)

tensor([[ 0.5285,  0.5285,  0.5285],
        [-0.8534, -0.8534, -0.8534],
        [ 0.8717,  0.8717,  0.8717]])

In [67]:
2 * (torch.exp(torch.tensor([2.0])) - 1) * 2

tensor([25.5562])

In [44]:
result_vectorized

tensor([1.0000, 0.9303, 0.8444, 0.8637, 0.8861, 0.8624, 0.8639, 0.8791, 0.8673,
        0.8643, 0.8757, 0.8697, 0.8648, 0.8736, 0.8710, 0.8654, 0.8720, 0.8718,
        0.8661, 0.8708, 0.8722, 0.8668, 0.8698, 0.8724, 0.8676, 0.8691, 0.8723,
        0.8683, 0.8685, 0.8720, 0.8691, 0.8682, 0.8716, 0.8697, 0.8680, 0.8712,
        0.8702, 0.8680, 0.8707, 0.8706, 0.8681, 0.8702, 0.8709, 0.8683, 0.8698,
        0.8711, 0.8686, 0.8694, 0.8711, 0.8689, 0.8691, 0.8710, 0.8693, 0.8688,
        0.8709, 0.8697, 0.8687, 0.8706, 0.8700, 0.8686, 0.8704, 0.8703, 0.8687,
        0.8701, 0.8705, 0.8688, 0.8698, 0.8706, 0.8689, 0.8695, 0.8707, 0.8692,
        0.8693, 0.8707, 0.8694, 0.8691, 0.8705, 0.8697, 0.8692, 0.8708, 0.8699,
        0.8689, 0.8703, 0.8701, 0.8689, 0.8700, 0.8703, 0.8690, 0.8698, 0.8704,
        0.8691, 0.8696, 0.8705, 0.8693, 0.8694, 0.8705, 0.8695, 0.8692, 0.8705,
        0.8697, 0.8691, 0.8704, 0.8699, 0.8690, 0.8702, 0.8702, 0.8690, 0.8700,
        0.8703, 0.8690, 0.8698, 0.8704, 

In [45]:
integrand(torch.tensor(3)).shape

torch.Size([1, 400])

In [47]:
torch.tensor([3,5,6]).reshape(1,-1)

torch.Size([1, 3])

In [52]:
torch.tensor(3).repeat(3)

tensor([3, 3, 3])

In [56]:
integrand(torch.tensor(3))

tensor([9, 9, 9])

# Test new algorithm

In [1]:
import torch
import torch.nn as nn
from typing_extensions import Literal
import torch.nn.functional as F
from typing import Optional
import numpy as np
from scipy.spatial.distance import cdist
from scvi.nn import Encoder, FCLayers
import scvelo as scv
import scanpy as sc
import pandas as pd
import sctour as rgv
import torchquad as tq
from torchquad import Boole
simp = tq.Simpson()

Global seed set to 0
/Users/weixu.wang/miniconda3/envs/RegVelo/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/Users/weixu.wang/miniconda3/envs/RegVelo/lib/python3.10/site-packages/flax/core/frozen_dict.py:169: FutureWarning: jax.tree_util.register_keypaths is deprecated, and will be removed in a future release. Please use `register_pytree_with_keys()` instead.
  jax.tree_util.register_keypaths(


In [2]:
scv.set_figure_params()

In [3]:
adata = sc.read_h5ad("dataset_branch_v2.h5ad")

In [4]:
adata

AnnData object with n_obs × n_vars = 1000 × 280
    obs: 'step_ix', 'simulation_i', 'sim_time'
    var: 'module_id', 'basal', 'burn', 'independence', 'color', 'is_tf', 'is_hk', 'transcription_rate', 'splicing_rate', 'translation_rate', 'mrna_halflife', 'protein_halflife', 'mrna_decay_rate', 'protein_decay_rate', 'max_premrna', 'max_mrna', 'max_protein', 'mol_premrna', 'mol_mrna', 'mol_protein'
    uns: 'network', 'regulators', 'skeleton', 'targets', 'traj_dimred_segments', 'traj_milestone_network', 'traj_progressions'
    obsm: 'dimred'
    layers: 'counts_protein', 'counts_spliced', 'counts_unspliced', 'logcounts', 'rna_velocity'

In [5]:
def sanity_check(adata):
    reg_index = [i in adata.var.index.values for i in adata.uns["regulators"]]
    tar_index = [i in adata.var.index.values for i in adata.uns["targets"]]
    adata.uns["regulators"] = adata.uns["regulators"][reg_index]
    adata.uns["targets"] = adata.uns["targets"][tar_index]
    W = adata.uns["skeleton"]
    W = W[reg_index,:]
    W = W[:,tar_index]
    adata.uns["skeleton"] = W
    W = adata.uns["network"]
    W = W[reg_index,:]
    W = W[:,tar_index]
    adata.uns["network"] = W
    
    regulators = adata.uns["regulators"][adata.uns["skeleton"].sum(1) > 0]
    targets = adata.uns["targets"][adata.uns["skeleton"].sum(0) > 0]

    W = pd.DataFrame(adata.uns["skeleton"],index = adata.uns["regulators"],columns = adata.uns["targets"])
    W = W.loc[regulators,targets]
    adata.uns["skeleton"] = W
    W = pd.DataFrame(adata.uns["network"],index = adata.uns["regulators"],columns = adata.uns["targets"])
    W = W.loc[regulators,targets]
    adata.uns["network"] = W
    
    adata.uns["regulators"] = regulators
    adata.uns["targets"] = targets
    
    adata = adata[:,np.unique(adata.uns["regulators"].tolist()+adata.uns["targets"].tolist())].copy()
    
    return adata

In [6]:
adata.uns["skeleton"].shape

(280, 280)

In [7]:
adata.X = adata.X.copy()
adata.layers["spliced"] = adata.layers["counts_spliced"].copy()
adata.layers["unspliced"] = adata.layers["counts_unspliced"].copy()

In [8]:
scv.pp.filter_and_normalize(adata, min_shared_counts=5, n_top_genes=280)
scv.pp.moments(adata, n_pcs=30, n_neighbors=30)

Filtered out 14 genes that are detected 5 counts (shared).
Normalized count data: X, spliced, unspliced.
Skip filtering by dispersion since number of variables are less than `n_top_genes`.
computing neighbors
    finished (0:00:01) --> added 
    'distances' and 'connectivities', weighted adjacency matrices (adata.obsp)
computing moments based on connectivities
    finished (0:00:00) --> added 
    'Ms' and 'Mu', moments of un/spliced abundances (adata.layers)


In [9]:
adata.layers["Mu"].max()

1086.6066

In [10]:
adata.X = np.log1p(adata.X.copy())

In [11]:
adata = sanity_check(adata)

In [12]:
adata.uns["skeleton"].shape

(135, 250)

In [13]:
adata.layers["Ms"].max()

39747.324

In [14]:
W = adata.uns["skeleton"].copy()

In [15]:
import torch
W = torch.tensor(np.array(W)).int()

In [16]:
W.shape

torch.Size([135, 250])

In [17]:
rgv_m = rgv.train.Trainer(adata, W=W.T,early_stopping = False, nepoch = 200, solver = "AdaBelief", lr = 0.01,wt_decay=0.01,T_max=300,batch_size=128,grad_clip = 5,alpha_recon_reg = 1)

In [18]:
class alpha_encoder(nn.Module):
    """ 
    encode the time dependent alpha (f)
    time dependent transcription rate is determined by upstream emulator

    """                 
    def __init__(
        self,
        n_int: int = 5,
        alpha_unconstr_init: torch.Tensor = None,
        W: torch.Tensor = (torch.FloatTensor(5, 5).uniform_() > 0.5).int(),
        W_int: torch.Tensor = None,
        log_h_int: torch.Tensor = None,
        global_time: bool = False,
    ):
        device = W.device
        super().__init__()
        self.n_int = n_int
        if global_time:
            self.log_h = torch.nn.Parameter(torch.randn(W.shape[1]))
            self.log_phi = torch.nn.Parameter(torch.randn(W.shape[1]))
            self.tau = torch.nn.Parameter(torch.randn(W.shape[1]))
            self.o = torch.nn.Parameter(torch.randn(W.shape[1]))
        else:
            self.log_h = torch.nn.Parameter(log_h_int.repeat(W.shape[0],1)*W)
            self.log_phi = torch.nn.Parameter(torch.ones(W.shape).to(device)*W)
            self.tau = torch.nn.Parameter(torch.ones(W.shape).to(device)*W*10)
            self.o = torch.nn.Parameter(torch.ones(W.shape).to(device)*W)

        self.mask_m = W
        self.global_time = global_time

        ## initialize grn
        self.grn = torch.nn.Parameter(W_int*self.mask_m)
        
        ## initilize gamma and beta
        self.beta_mean_unconstr = torch.nn.Parameter(0.5 * torch.ones(n_int))
        self.gamma_mean_unconstr = torch.nn.Parameter(-1 * torch.ones(n_int))
        self.alpha_unconstr_bias = torch.nn.Parameter(torch.zeros(n_int))
        self.alpha_unconstr_max = torch.nn.Parameter(torch.randn(n_int))
        # calculating emulating matrix
    
    ### define hook to froze the parameters
    def _set_mask_grad(self):
        self.hooks_grn = []
        if not self.global_time:
            self.hooks_log_h = []
            self.hooks_log_phi = []
            self.hooks_tau = []
            self.hooks_o = []
        #mask_m = self.mask_m
        
        def _hook_mask_no_regulator(grad):
            return grad * self.mask_m

        w_grn = self.grn.register_hook(_hook_mask_no_regulator)
        self.hooks_grn.append(w_grn)
        if not self.global_time:
            w_log_h = self.log_h.register_hook(_hook_mask_no_regulator)
            w_log_phi = self.log_phi.register_hook(_hook_mask_no_regulator)
            w_tau = self.tau.register_hook(_hook_mask_no_regulator)
            w_o = self.o.register_hook(_hook_mask_no_regulator)

            self.hooks_log_h.append(w_log_h)
            self.hooks_log_phi.append(w_log_phi)
            self.hooks_tau.append(w_tau)
            self.hooks_o.append(w_o)

    def emulator(t,log_h_v,log_phi_v,tau_v,o_v):
        pre = torch.exp(log_h_v)*torch.exp(-torch.exp(phi_v)*(t-tau_v)**2)+o_v
        
        return pre

    def emulation_all(self,t: torch.Tensor = None):
        if self.global_time:
            # broadcasting the time t
            t = t.repeat((self.mask_m.shape[0],1))

        emulate_m = torch.zeros([self.mask_m.shape[0], self.mask_m.shape[1], t.shape[1]])

        h = torch.exp(self.log_h)
        phi = torch.exp(self.log_phi)
        for i in range(t.shape[1]):
            # for each time stamps, predict the emulator predict value
            tt = t[:,i]
            emu = h * torch.exp(-phi*(tt.reshape((len(tt),1))-self.tau)**2) + self.o
            emulate_m[:,:,i] = emu

        return emulate_m


    def forward(self,t,g):
        ## Encode 

        if self.global_time:
            u = u[locate]
            s = s[locate]
            ## when use global time, t is a single value
            T = t.repeat((dim,1))

            ## calculate emulator vector
            h = torch.exp(self.log_h)
            phi = torch.exp(self.log_phi)
            emu = h[locate,:] * torch.exp(-phi[locate,:]*(T.reshape((dim,1))-self.tau[locate,:])**2) + self.o[locate,:]
            
            ## Use the Emulator matrix to predict alpha
            emu = emu * self.grn[locate,:]
            alpha_unconstr = emu.sum(dim=1)
            alpha_unconstr = alpha_unconstr + self.alpha_unconstr[locate]
            
            ## Generate kinetic rate
            beta = torch.clamp(F.softplus(self.beta_mean_unconstr[locate]), 0, 50)
            gamma = torch.clamp(F.softplus(self.gamma_mean_unconstr[locate]), 0, 50)
            alpha = torch.clamp(F.softplus(alpha_unconstr),0,50)

            ## Predict velocity
            du = alpha - beta*u
            ds = beta*u - gamma*s

            du = du.reshape((dim,1))
            ds = ds.reshape((dim,1))

            v = torch.concatenate([du,ds],axis = 1)

        else:
            ## calculate emulator value
            ## output the f_g(t)
            
            ## Build Emulator matrix for gene g
            
            h = torch.exp(self.log_h)[g,:].view(-1)
            phi = torch.exp(self.log_phi)[g,:].view(-1)
            tau = self.tau[g,:].view(-1)
            o = self.o[g,:].view(-1)
            w = self.grn[g,:].view(-1)
            bias = self.alpha_unconstr_bias[g]
            print(tau)
            #emu = h[locate,:] * torch.exp(-phi[locate,:]*(T.reshape((dim,1))-self.tau[locate,:])**2) + self.o[locate,:]
            emu = h * torch.exp(-phi*(t - tau)**2) + o

            ## Use the Emulator matrix to predict alpha
            #emu = emu * self.grn[locate,:]
            emu = emu * w
            
            alpha_unconstr = emu.sum()
            #alpha_unconstr = alpha_unconstr + self.alpha_unconstr_bias[locate]
            alpha_unconstr = alpha_unconstr + bias

            ## Generate transcription kinetic rate for time t
            alpha = torch.clamp(alpha_unconstr,0,)
            alpha = F.softsign(alpha)

        return alpha
    


class alpha_encoder2(nn.Module):
    """ 
    encode the time dependent alpha (f)
    time dependent transcription rate is determined by upstream emulator

    """                 
    def __init__(
        self,
        n_int: int = 5,
        alpha_unconstr_init: torch.Tensor = None,
        W: torch.Tensor = (torch.FloatTensor(5, 5).uniform_() > 0.5).int(),
        W_int: torch.Tensor = None,
        log_h_int: torch.Tensor = None,
        global_time: bool = False,
    ):
        device = W.device
        super().__init__()
        self.n_int = n_int
        self.device = device
        if global_time:
            self.log_h = torch.nn.Parameter(torch.randn(W.shape[1]))
            self.log_phi = torch.nn.Parameter(torch.randn(W.shape[1]))
            self.tau = torch.nn.Parameter(torch.randn(W.shape[1]))
            self.o = torch.nn.Parameter(torch.randn(W.shape[1]))
        else:
            self.log_h = torch.nn.Parameter(log_h_int.repeat(W.shape[0],1)*W)
            self.log_phi = torch.nn.Parameter(torch.ones(W.shape).to(device)*W)
            self.tau = torch.nn.Parameter(torch.ones(W.shape).to(device)*W*10)
            self.o = torch.nn.Parameter(torch.ones(W.shape).to(device)*W)

        self.mask_m = W
        self.global_time = global_time

        ## initialize grn
        self.grn = torch.nn.Parameter(W_int*self.mask_m)
        
        ## initilize gamma and beta
        self.beta_mean_unconstr = torch.nn.Parameter(0.5 * torch.ones(n_int).to(device))
        self.gamma_mean_unconstr = torch.nn.Parameter(-1 * torch.ones(n_int).to(device))
        self.alpha_unconstr_bias = torch.nn.Parameter(torch.zeros(n_int).to(device))
        self.alpha_unconstr_max = torch.nn.Parameter(torch.randn(n_int).to(device))
        # calculating emulating matrix
    
    ### define hook to froze the parameters
    def _set_mask_grad(self):
        self.hooks_grn = []
        if not self.global_time:
            self.hooks_log_h = []
            self.hooks_log_phi = []
            self.hooks_tau = []
            self.hooks_o = []
        #mask_m = self.mask_m
        
        def _hook_mask_no_regulator(grad):
            return grad * self.mask_m

        w_grn = self.grn.register_hook(_hook_mask_no_regulator)
        self.hooks_grn.append(w_grn)
        if not self.global_time:
            w_log_h = self.log_h.register_hook(_hook_mask_no_regulator)
            w_log_phi = self.log_phi.register_hook(_hook_mask_no_regulator)
            w_tau = self.tau.register_hook(_hook_mask_no_regulator)
            w_o = self.o.register_hook(_hook_mask_no_regulator)

            self.hooks_log_h.append(w_log_h)
            self.hooks_log_phi.append(w_log_phi)
            self.hooks_tau.append(w_tau)
            self.hooks_o.append(w_o)

    def emulator(t,log_h_v,log_phi_v,tau_v,o_v):
        pre = torch.exp(log_h_v)*torch.exp(-torch.exp(phi_v)*(t-tau_v)**2)+o_v
        
        return pre

    def emulation_all(self,t: torch.Tensor = None):
        if self.global_time:
            # broadcasting the time t
            t = t.repeat((self.mask_m.shape[0],1))

        emulate_m = torch.zeros([self.mask_m.shape[0], self.mask_m.shape[1], t.shape[1]])

        h = torch.exp(self.log_h)
        phi = torch.exp(self.log_phi)
        for i in range(t.shape[1]):
            # for each time stamps, predict the emulator predict value
            tt = t[:,i]
            emu = h * torch.exp(-phi*(tt.reshape((len(tt),1))-self.tau)**2) + self.o
            emulate_m[:,:,i] = emu

        return emulate_m


    def forward(self,t,t_scale,t0):
        ## Encode 

        if self.global_time:
            u = u[locate]
            s = s[locate]
            ## when use global time, t is a single value
            T = t.repeat((dim,1))

            ## calculate emulator vector
            h = torch.exp(self.log_h)
            phi = torch.exp(self.log_phi)
            emu = h[locate,:] * torch.exp(-phi[locate,:]*(T.reshape((dim,1))-self.tau[locate,:])**2) + self.o[locate,:]
            
            ## Use the Emulator matrix to predict alpha
            emu = emu * self.grn[locate,:]
            alpha_unconstr = emu.sum(dim=1)
            alpha_unconstr = alpha_unconstr + self.alpha_unconstr[locate]
            
            ## Generate kinetic rate
            beta = torch.clamp(F.softplus(self.beta_mean_unconstr[locate]), 0, 50)
            gamma = torch.clamp(F.softplus(self.gamma_mean_unconstr[locate]), 0, 50)
            alpha = torch.clamp(F.softplus(alpha_unconstr),0,50)

            ## Predict velocity
            du = alpha - beta*u
            ds = beta*u - gamma*s

            du = du.reshape((dim,1))
            ds = ds.reshape((dim,1))

            v = torch.concatenate([du,ds],axis = 1)

        else:
            ## calculate emulator value
            ## output the f_g(t)
            
            ## Build Emulator matrix for gene g
            t = t.to(self.device)
            h = torch.exp(self.log_h)
            phi = torch.exp(self.log_phi)
            tau = self.tau
            o = self.o
            w = self.grn
            bias = self.alpha_unconstr_bias

            #emu = h[locate,:] * torch.exp(-phi[locate,:]*(T.reshape((dim,1))-self.tau[locate,:])**2) + self.o[locate,:]
            rt = t*t_scale+t0
            if len(rt.shape) == 1:
                rt = rt.reshape(1,-1)

            ### create new dimensions for parameters
            phi_rep = phi.repeat(rt.shape[0], 1, 1)
            phi_rep = phi_rep.view(rt.shape[0], phi.shape[0], phi.shape[1])
            
            o_rep = o.repeat(rt.shape[0], 1, 1)
            o_rep = o_rep.view(rt.shape[0], o.shape[0], o.shape[1])
            
            h_rep = h.repeat(rt.shape[0], 1, 1)
            h_rep = h_rep.view(rt.shape[0], h.shape[0], h.shape[1])
            
            tau_rep = tau.repeat(rt.shape[0], 1, 1)
            tau_rep = tau_rep.view(rt.shape[0], tau.shape[0], tau.shape[1])
            
            emu = h_rep * torch.exp(-phi_rep*(rt.unsqueeze(2) - tau_rep)**2) + o_rep
            
            ## Use the Emulator matrix to predict alpha
            #emu = emu * self.grn[locate,:]
            
            w_rep = w.repeat(rt.shape[0], 1, 1)
            w_rep = w_rep.view(rt.shape[0], w.shape[0], w.shape[1])
            emu = emu * w_rep
            
            alpha_unconstr = emu.sum(dim=2)
            #alpha_unconstr = alpha_unconstr + self.alpha_unconstr_bias[locate]
            bias_rep = bias.repeat(rt.shape[0], 1)
            alpha_unconstr = alpha_unconstr + bias_rep

            ## Generate transcription kinetic rate for time t
            alpha = torch.clamp(alpha_unconstr,0,)
            alpha = F.softsign(alpha)

        return alpha
    
def SolveInitialValueProblem(f_t, x0, t0, t_eval):
    
    ## generate the prediction of unspliced/spliced readout at time t for every gene
    ## use torchquad integral, different with torchode, the t_eval no longer need to be ordered
    ## Now t is the G genes time in one cell
    
    ## get the kinetic parameters
    beta = torch.clamp(F.softplus(f_t.beta_mean_unconstr), 0, 50)
    gamma = torch.clamp(F.softplus(f_t.gamma_mean_unconstr), 0, 50)
    alpha_max = torch.clamp(F.softplus(f_t.alpha_unconstr_max),0, 50)

    ## define integral function
    def integral_operator(tt,f_t, t0, beta, gamma):
        t_scale = tt - t0 # when t0 is non-zero, minus t0 to make sure time start from 0
        f_beta = lambda t: f_t(t,t_scale,t0)*torch.exp(beta*(t*t_scale+t0))*t_scale
        f_gamma = lambda t: f_t(t,t_scale,t0)*torch.exp(gamma*(t*t_scale+t0))*t_scale
        integration_domain = [[0,1]]
        int_beta = simp.integrate(f_beta, dim=1, N=101, integration_domain=integration_domain)
        int_gamma = simp.integrate(f_gamma, dim=1, N=101, integration_domain=integration_domain)
        return torch.cat((int_beta,int_gamma))
        
    #def integral_alpha_gamma(tt,f_t,t0, gamma):
    #    t_scale = tt - t0 # when t0 is non-zero, minus t0 to make sure time start from 0
    #    f_i = lambda t: f_t(t,t_scale,t0)*torch.exp(gamma*t)
    #    integration_domain = [[0,1]]
    #    result = simp.integrate(f_i, dim=1, N=101, integration_domain=integration_domain)
    #    return result

    ## get the initial condition (i.e. u,s = 0,0)
    u0 = x0[:,0]
    s0 = x0[:,1]
    
    ## generate readout for each target gene
    ## calculate integral for gene g
    
    integral = list(map(lambda tt: integral_operator(tt=tt,f_t=f_t,t0=t0,beta = beta, gamma = gamma), t_eval))
    #integral = [integral_operator(tt=t_eval[i,:],f_t=f_t,t0=t0,beta = beta, gamma = gamma) for i in range(t_eval.shape[0])]
    integral = torch.stack(integral)
    integral_tensor_alpha_beta = integral[:,:t_eval.shape[1]]
    integral_tensor_alpha_gamma = integral[:,t_eval.shape[1]:]
    
    pre_u = u0*torch.exp(-beta*t_eval) + alpha_max*torch.exp(-beta*t_eval)*integral_tensor_alpha_beta
    pre_s = s0*torch.exp(-gamma*t_eval) + \
        ( (alpha_max*beta)/(gamma - beta) )*(torch.exp(-beta*t_eval)*integral_tensor_alpha_beta - torch.exp(-gamma*t_eval)*integral_tensor_alpha_gamma) + \
        ( (beta*u0)/(gamma - beta) )*(torch.exp(-beta*t_eval) - torch.exp(-gamma*t_eval))

        
    return pre_u,pre_s

In [19]:
f_t2 = alpha_encoder2(n_int = rgv_m.model.n_targets, alpha_unconstr_init = rgv_m.model.f_t.alpha_unconstr_bias,log_h_int = rgv_m.model.f_t.log_h[0,:],
                    W = W.T, W_int = rgv_m.model.f_t.grn)

In [20]:
m = nn.Sigmoid()
t = m(torch.randn(30,250))

In [21]:
t = t*20

In [22]:
t = t.to("cpu")

In [23]:
x0 = torch.zeros((250,2))
t0 = torch.zeros((250))

In [24]:
import datetime
starttime = datetime.datetime.now()
u2,s2 = SolveInitialValueProblem(f_t2,x0,t0,t)
endtime = datetime.datetime.now()
print(endtime - starttime)

0:00:01.396217


In [25]:
u2

tensor([[0.2129, 0.2691, 0.2908,  ..., 0.0000, 0.0591, 0.1418],
        [0.2549, 0.2802, 0.3133,  ..., 0.0000, 0.0591, 0.1597],
        [0.3160, 0.2574, 0.3120,  ..., 0.0000, 0.0589, 0.2037],
        ...,
        [0.2501, 0.2744, 0.4935,  ..., 0.0000, 0.0604, 0.1512],
        [0.2348, 0.3037, 0.3112,  ..., 0.0000, 0.0593, 0.1512],
        [0.2126, 0.2720, 0.3122,  ..., 0.0000, 0.0848, 0.1759]],
       grad_fn=<AddBackward0>)

# use broadcast to 3D

In [26]:
from autoray import numpy as anp
from loguru import logger
from autoray import infer_backend
from torchquad.integration.utils import _setup_integration_domain
import torchquad as tq

class alpha_encoder3(nn.Module):
    """ 
    encode the time dependent alpha (f)
    time dependent transcription rate is determined by upstream emulator

    """                 
    def __init__(
        self,
        n_int: int = 5,
        alpha_unconstr_init: torch.Tensor = None,
        W: torch.Tensor = (torch.FloatTensor(5, 5).uniform_() > 0.5).int(),
        W_int: torch.Tensor = None,
        log_h_int: torch.Tensor = None,
        global_time: bool = False,
    ):
        device = W.device
        super().__init__()
        self.n_int = n_int
        if global_time:
            self.log_h = torch.nn.Parameter(torch.randn(W.shape[1]))
            self.log_phi = torch.nn.Parameter(torch.randn(W.shape[1]))
            self.tau = torch.nn.Parameter(torch.randn(W.shape[1]))
            self.o = torch.nn.Parameter(torch.randn(W.shape[1]))
        else:
            self.log_h = torch.nn.Parameter(log_h_int.repeat(W.shape[0],1)*W)
            self.log_phi = torch.nn.Parameter(torch.ones(W.shape).to(device)*W)
            self.tau = torch.nn.Parameter(torch.ones(W.shape).to(device)*W*10)
            self.o = torch.nn.Parameter(torch.ones(W.shape).to(device)*W)

        self.mask_m = W
        self.global_time = global_time
        self.device = device
        ## initialize grn
        self.grn = torch.nn.Parameter(W_int*self.mask_m)
        
        ## initilize gamma and beta
        self.beta_mean_unconstr = torch.nn.Parameter(0.5 * torch.ones(n_int).to(device))
        self.gamma_mean_unconstr = torch.nn.Parameter(-1 * torch.ones(n_int).to(device))
        self.alpha_unconstr_bias = torch.nn.Parameter(torch.zeros(n_int).to(device))
        self.alpha_unconstr_max = torch.nn.Parameter(torch.randn(n_int).to(device))
        
        # create integrator
        integration_domain = [[0,1]]
        simp = tq.Simpson()
        integration_domain = _setup_integration_domain(dim=1, integration_domain=integration_domain, backend="torch")
        grid_points, hs, n_per_dim = simp.calculate_grid(N=101, integration_domain=integration_domain)
        grid_points = grid_points.to(mps_device)
        self.grid_points = grid_points
        self.hs = hs
        self.n_per_dim = n_per_dim
    
    ### define hook to froze the parameters
    def _set_mask_grad(self):
        self.hooks_grn = []
        if not self.global_time:
            self.hooks_log_h = []
            self.hooks_log_phi = []
            self.hooks_tau = []
            self.hooks_o = []
        #mask_m = self.mask_m
        
        def _hook_mask_no_regulator(grad):
            return grad * self.mask_m

        w_grn = self.grn.register_hook(_hook_mask_no_regulator)
        self.hooks_grn.append(w_grn)
        if not self.global_time:
            w_log_h = self.log_h.register_hook(_hook_mask_no_regulator)
            w_log_phi = self.log_phi.register_hook(_hook_mask_no_regulator)
            w_tau = self.tau.register_hook(_hook_mask_no_regulator)
            w_o = self.o.register_hook(_hook_mask_no_regulator)

            self.hooks_log_h.append(w_log_h)
            self.hooks_log_phi.append(w_log_phi)
            self.hooks_tau.append(w_tau)
            self.hooks_o.append(w_o)

    def emulator(t,log_h_v,log_phi_v,tau_v,o_v):
        pre = torch.exp(log_h_v)*torch.exp(-torch.exp(phi_v)*(t-tau_v)**2)+o_v
        
        return pre

    def emulation_all(self,t: torch.Tensor = None):
        if self.global_time:
            # broadcasting the time t
            t = t.repeat((self.mask_m.shape[0],1))

        emulate_m = torch.zeros([self.mask_m.shape[0], self.mask_m.shape[1], t.shape[1]])

        h = torch.exp(self.log_h)
        phi = torch.exp(self.log_phi)
        for i in range(t.shape[1]):
            # for each time stamps, predict the emulator predict value
            tt = t[:,i]
            emu = h * torch.exp(-phi*(tt.reshape((len(tt),1))-self.tau)**2) + self.o
            emulate_m[:,:,i] = emu

        return emulate_m


    def forward(self,t,t_scale,t0):
        ## Encode 

        if self.global_time:
            u = u[locate]
            s = s[locate]
            ## when use global time, t is a single value
            T = t.repeat((dim,1))

            ## calculate emulator vector
            h = torch.exp(self.log_h)
            phi = torch.exp(self.log_phi)
            emu = h[locate,:] * torch.exp(-phi[locate,:]*(T.reshape((dim,1))-self.tau[locate,:])**2) + self.o[locate,:]
            
            ## Use the Emulator matrix to predict alpha
            emu = emu * self.grn[locate,:]
            alpha_unconstr = emu.sum(dim=1)
            alpha_unconstr = alpha_unconstr + self.alpha_unconstr[locate]
            
            ## Generate kinetic rate
            sp = nn.Softplus()
            beta = torch.clamp(sp(self.beta_mean_unconstr[locate]), 0, 50)
            gamma = torch.clamp(sp(self.gamma_mean_unconstr[locate]), 0, 50)
            alpha = torch.clamp(sp(alpha_unconstr),0,50)

            ## Predict velocity
            du = alpha - beta*u
            ds = beta*u - gamma*s

            du = du.reshape((dim,1))
            ds = ds.reshape((dim,1))

            v = torch.concatenate([du,ds],axis = 1)

        else:
            ## calculate emulator value
            ## output the f_g(t)
            
            ## Build Emulator matrix for gene g
            t = t.to(self.device)
            h = torch.exp(self.log_h)
            phi = torch.exp(self.log_phi)
            tau = self.tau
            o = self.o
            w = self.grn
            bias = self.alpha_unconstr_bias

            #emu = h[locate,:] * torch.exp(-phi[locate,:]*(T.reshape((dim,1))-self.tau[locate,:])**2) + self.o[locate,:]
            #rt = t*t_scale+t0
            rt = torch.einsum('i,jk->ijk', t.view(-1), t_scale) + t0
            
            if len(rt.shape) == 2:
                #rt = rt.reshape(1,-1)
                rt = rt.unsqueeze(0)
                
            ### create new dimensions for parameters
            phi = phi.expand(rt.shape[0], rt.shape[1],phi.shape[0], phi.shape[1])
            o = o.expand(rt.shape[0], rt.shape[1],o.shape[0], o.shape[1])
            h = h.expand(rt.shape[0], rt.shape[1],h.shape[0], h.shape[1])
            tau = tau.expand(rt.shape[0], rt.shape[1],tau.shape[0], tau.shape[1])
            
            emu = h * torch.exp(-phi*(rt.unsqueeze(3) - tau)**2) + o
            
            ## Use the Emulator matrix to predict alpha
            #emu = emu * self.grn[locate,:]
            w = w.expand(rt.shape[0], rt.shape[1],w.shape[0], w.shape[1])
            emu = emu * w
            
            alpha_unconstr = emu.sum(dim=3)
            #alpha_unconstr = alpha_unconstr + self.alpha_unconstr_bias[locate]
            bias = bias.expand(rt.shape[0], rt.shape[1], bias.shape[0])
            alpha_unconstr = alpha_unconstr + bias

            ## Generate transcription kinetic rate for time t
            alpha = torch.clamp(alpha_unconstr,0,)
            alpha = F.softsign(alpha)

        return alpha
    
def SolveInitialValueProblem(f_t, x0, t0, t_eval):
    
    ## generate the prediction of unspliced/spliced readout at time t for every gene
    ## use torchquad integral, different with torchode, the t_eval no longer need to be ordered
    ## Now t is the G genes time in one cell
    
    ## get the kinetic parameters
    beta = torch.clamp(F.softplus(f_t.beta_mean_unconstr), 0, 50)
    gamma = torch.clamp(F.softplus(f_t.gamma_mean_unconstr), 0, 50)
    alpha_max = torch.clamp(F.softplus(f_t.alpha_unconstr_max),0, 50)
    
    def calculate_result(simp, function_values, dim, n_per_dim, hs):
        """Apply the Composite Newton Cotes rule to calculate a result from the evaluated integrand.
        Args:
            function_values (backend tensor): Output of the integrand
            dim (int): Dimensionality
            n_per_dim (int): Number of grid slices per dimension
            hs (backend tensor): Distances between grid slices for each dimension
        Returns:
            backend tensor: Quadrature result
        """
        # Reshape the output to be [integrand_dim,N,N,...] points instead of [integrand_dim,dim*N] points
        integrand_shape = function_values.shape[1:]
        dim_shape = [n_per_dim] * dim
        new_shape = [*integrand_shape, *dim_shape]
        # We need to use einsum instead of just reshape here because reshape does not move the axis - it only reshapes.
        # So the first line generates a character string for einsum, followed by moving the first dimension i.e `dim*N`
        # to the end.  Finally we reshape the resulting object so that instead of the last dimension being `dim*N`, it is
        # `N,N,...` as desired.
        einsum = "".join([chr(i + 65) for i in range(len(function_values.shape))])
        reshaped_function_values = anp.einsum(
            f"{einsum}->{einsum[1:]}{einsum[0]}", function_values
        )
        reshaped_function_values = reshaped_function_values.reshape(new_shape)
        assert new_shape == list(
            reshaped_function_values.shape
        ), f"reshaping produced shape {reshaped_function_values.shape}, expected shape was {new_shape}"
        logger.debug("Computing areas.")

        result = simp._apply_composite_rule(reshaped_function_values, dim, hs)

        logger.opt(lazy=True).info(
            "Computed integral: {result}", result=lambda: str(result)
        )
        return result

    ## define integral function
    u0 = x0[:,0]
    s0 = x0[:,1]
    
    t_scale = t_eval - t0 # when t0 is non-zero, minus t0 to make sure time start from 0
    f_beta = lambda t: f_t(t,t_scale,t0)*torch.exp(beta*((torch.einsum('i,jk->ijk', t.view(-1), t_scale) + t0)))*t_scale
    f_gamma = lambda t: f_t(t,t_scale,t0)*torch.exp(gamma*((torch.einsum('i,jk->ijk', t.view(-1), t_scale) + t0)))*t_scale

    function_values1, num_points = simp.evaluate_integrand(f_beta, f_t.grid_points)
    function_values2, _ = simp.evaluate_integrand(f_gamma, f_t.grid_points)
    simp._nr_of_fevals = num_points
    integral_tensor_alpha_beta = calculate_result(simp,function_values1,1,f_t.n_per_dim,f_t.hs)
    integral_tensor_alpha_gamma = calculate_result(simp,function_values2,1,f_t.n_per_dim,f_t.hs)
        
    #def integral_alpha_gamma(tt,f_t,t0, gamma):
    #    t_scale = tt - t0 # when t0 is non-zero, minus t0 to make sure time start from 0
    #    f_i = lambda t: f_t(t,t_scale,t0)*torch.exp(gamma*t)
    #    integration_domain = [[0,1]]
    #    result = simp.integrate(f_i, dim=1, N=101, integration_domain=integration_domain)
    #    return result

    ## get the initial condition (i.e. u,s = 0,0)
    
    ## generate readout for each target gene
    ## calculate integral for gene g
    
    #integral = list(map(lambda tt: integral_operator(tt=tt,f_t=f_t,t0=t0,beta = beta, gamma = gamma), t_eval))
    #integral = [integral_operator(tt=t_eval[i,:],f_t=f_t,t0=t0,beta = beta, gamma = gamma) for i in range(t_eval.shape[0])]
    #integral = torch.stack(integral)
    #integral_tensor_alpha_beta, integral_tensor_alpha_gamma = integral_operator(t_eval, f_t, t0 = t0, beta = beta, gamma = gamma)
    
    #pre_u = u0*torch.exp(-beta*t_eval) + alpha_max*torch.exp(-beta*t_eval)*integral_tensor_alpha_beta
    #pre_s = s0*torch.exp(-gamma*t_eval) + \
    #    ( (alpha_max*beta)/(gamma - beta) )*(torch.exp(-beta*t_eval)*integral_tensor_alpha_beta - torch.exp(-gamma*t_eval)*integral_tensor_alpha_gamma) + \
    #    ( (beta*u0)/(gamma - beta) )*(torch.exp(-beta*t_eval) - torch.exp(-gamma*t_eval))

        
    return integral_tensor_alpha_beta, integral_tensor_alpha_gamma

In [27]:
def calculate_result(simp, function_values, dim, n_per_dim, hs):
    """Apply the Composite Newton Cotes rule to calculate a result from the evaluated integrand.
    Args:
        function_values (backend tensor): Output of the integrand
        dim (int): Dimensionality
        n_per_dim (int): Number of grid slices per dimension
        hs (backend tensor): Distances between grid slices for each dimension
    Returns:
        backend tensor: Quadrature result
    """
    # Reshape the output to be [integrand_dim,N,N,...] points instead of [integrand_dim,dim*N] points
    integrand_shape = function_values.shape[1:]
    dim_shape = [n_per_dim] * dim
    new_shape = [*integrand_shape, *dim_shape]
    # We need to use einsum instead of just reshape here because reshape does not move the axis - it only reshapes.
    # So the first line generates a character string for einsum, followed by moving the first dimension i.e `dim*N`
    # to the end.  Finally we reshape the resulting object so that instead of the last dimension being `dim*N`, it is
    # `N,N,...` as desired.
    einsum = "".join([chr(i + 65) for i in range(len(function_values.shape))])
    reshaped_function_values = anp.einsum(
        f"{einsum}->{einsum[1:]}{einsum[0]}", function_values
    )
    reshaped_function_values = reshaped_function_values.reshape(new_shape)
    assert new_shape == list(
        reshaped_function_values.shape
    ), f"reshaping produced shape {reshaped_function_values.shape}, expected shape was {new_shape}"
    logger.debug("Computing areas.")

    result = simp._apply_composite_rule(reshaped_function_values, dim, hs)

    logger.opt(lazy=True).info(
        "Computed integral: {result}", result=lambda: str(result)
    )
    return result

In [28]:
mps_device = torch.device("mps")

In [29]:
f_t3 = alpha_encoder3(n_int = rgv_m.model.n_targets, alpha_unconstr_init = rgv_m.model.f_t.alpha_unconstr_bias.to(mps_device),log_h_int = rgv_m.model.f_t.log_h[0,:].to(mps_device),
                    W = W.T.to(mps_device), W_int = rgv_m.model.f_t.grn.to(mps_device))

In [30]:
t0 = torch.zeros(t.shape).to(mps_device)

In [31]:
t = t.to(mps_device)
x0 = torch.zeros((250,2)).to(mps_device)

In [35]:
import datetime
starttime = datetime.datetime.now()
u,s = SolveInitialValueProblem(f_t3, x0, t0, t)
endtime = datetime.datetime.now()
print(endtime - starttime)

0:00:00.027449


In [34]:
beta = torch.clamp(F.softplus(f_t3.beta_mean_unconstr), 0, 50)
gamma = torch.clamp(F.softplus(f_t3.gamma_mean_unconstr), 0, 50)
alpha_max = torch.clamp(F.softplus(f_t3.alpha_unconstr_max),0, 50)
u0 = x0[:,0]
s0 = x0[:,1]
import datetime
starttime = datetime.datetime.now()
pre_u = u0*torch.exp(-beta*t) + alpha_max*torch.exp(-beta*t)*u
pre_s = (beta/(gamma - beta))*pre_u + s0*torch.exp(-gamma*t) - ( (alpha_max*beta)/(gamma - beta) )*torch.exp(-gamma*t)*s - ( (beta*u0)/(gamma - beta) )*torch.exp(-gamma*t)
endtime = datetime.datetime.now()
print(endtime - starttime)

0:00:00.057828


In [38]:
torch.mps.manual_seed(0)

In [71]:
pre_s = (beta/(gamma - beta))*pre_u + s0*torch.exp(-gamma*t) - ( (alpha_max*beta)/(gamma - beta) )*torch.exp(-gamma*t)*s - ( (beta*u0)/(gamma - beta) )*torch.exp(-gamma*t)

In [74]:
pre_s

tensor([[1.8347, 1.7346, 1.2099,  ..., 0.0000, 0.0626, 0.1656],
        [2.7806, 3.2880, 3.2434,  ..., 0.0000, 0.0726, 0.4338],
        [2.4508, 1.2165, 2.3972,  ..., 0.0000, 0.0567, 0.3809],
        ...,
        [2.7734, 3.0816, 3.6759,  ..., 0.0000, 0.0763, 0.3489],
        [2.7273, 3.5057, 2.2039,  ..., 0.0000, 0.0736, 0.3372],
        [1.7256, 2.0781, 2.4848,  ..., 0.0000, 0.0743, 0.4364]],
       device='mps:0', grad_fn=<AddBackward0>)

In [32]:
def integral_operator(tt,f_t, t0, beta, gamma):
    t_scale = tt - t0 # when t0 is non-zero, minus t0 to make sure time start from 0
    f_beta = lambda t: f_t(t,t_scale,t0)*torch.exp(beta*((torch.einsum('i,jk->ijk', t.to(mps_device).view(-1), t_scale) + t0)))*t_scale
    f_gamma = lambda t: f_t(t,t_scale,t0)*torch.exp(gamma*((torch.einsum('i,jk->ijk', t.to(mps_device).view(-1), t_scale) + t0)))*t_scale
    integration_domain = [[0,1]]
    int_beta = simp.integrate(f_beta, dim=1, N=101, integration_domain=integration_domain,backend="torch")
    int_gamma = simp.integrate(f_gamma, dim=1, N=101, integration_domain=integration_domain,backend="torch")
    return int_beta, int_gamma

In [33]:
t_scale = t - t0
beta = torch.clamp(F.softplus(f_t3.beta_mean_unconstr), 0, 50)
gamma = torch.clamp(F.softplus(f_t3.gamma_mean_unconstr), 0, 50)
alpha_max = torch.clamp(F.softplus(f_t3.alpha_unconstr_max),0, 50)
f_beta = lambda t: f_t3(t,t_scale,t0)*torch.exp(beta*((torch.einsum('i,jk->ijk', t.view(-1), t_scale) + t0)))*t_scale
f_gamma = lambda t: f_t3(t,t_scale,t0)*torch.exp(gamma*((torch.einsum('i,jk->ijk', t.view(-1), t_scale) + t0)))*t_scale

In [70]:
import datetime
u0 = x0[:,0]
s0 = x0[:,1]
starttime = datetime.datetime.now()
function_values1, num_points = simp.evaluate_integrand(f_beta, f_t3.grid_points)
function_values2, num_points = simp.evaluate_integrand(f_gamma, f_t3.grid_points)
simp._nr_of_fevals = num_points
integral_tensor_alpha_beta = calculate_result(simp,function_values1,1,f_t3.n_per_dim,f_t3.hs)
integral_tensor_alpha_gamma = calculate_result(simp,function_values2,1,f_t3.n_per_dim,f_t3.hs)
pre_u = u0*torch.exp(-beta*t) + alpha_max*torch.exp(-beta*t)*integral_tensor_alpha_beta
pre_s = s0*torch.exp(-gamma*t) + \
    ( (alpha_max*beta)/(gamma - beta) )*(torch.exp(-beta*t)*integral_tensor_alpha_beta - torch.exp(-gamma*t)*integral_tensor_alpha_gamma) + \
    ( (beta*u0)/(gamma - beta) )*(torch.exp(-beta*t) - torch.exp(-gamma*t))
endtime = datetime.datetime.now()
print(endtime - starttime)

RuntimeError: MPS backend out of memory (MPS allocated: 14.23 GB, other allocations: 3.90 GB, max allowed: 18.13 GB). Tried to allocate 390.10 MB on private pool. Use PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0 to disable upper limit for memory allocations (may cause system failure).

In [139]:
import datetime
starttime = datetime.datetime.now()
integral_operator(t.to(mps_device),f_t3,t0.to(mps_device),beta,gamma)
endtime = datetime.datetime.now()
print(endtime - starttime)

0:00:01.858688


In [37]:
t_sample = m(torch.randn(101,1))
t_scale = t
t_sample = t_sample.to(f_t3.device)
t_scale = t_scale.to(f_t3.device)

In [132]:
f_beta = lambda t: f_t3(t,t_scale,t0)*torch.exp(beta*((torch.einsum('i,jk->ijk', t.to(mps_device).view(-1), t_scale) + t0)))*t_scale
f_gamma = lambda t: f_t3(t,t_scale,t0)*torch.exp(gamma*((torch.einsum('i,jk->ijk', t.to(mps_device).view(-1), t_scale) + t0)))*t_scale

In [133]:
import datetime
starttime = datetime.datetime.now()
f_beta(t_sample)
f_gamma(t_sample)
endtime = datetime.datetime.now()
print(endtime - starttime)

0:00:00.026669


In [30]:
F.softplus(f_t3.beta_mean_unconstr.to("cpu")).shape

torch.Size([250])

In [31]:
t_sample = m(torch.randn(101,1))
t_scale = t

In [32]:
t_sample = t_sample.to(f_t3.device)
t_scale = t_scale.to(f_t3.device)
h = torch.exp(f_t3.log_h)
phi = torch.exp(f_t3.log_phi)
tau = f_t3.tau
o = f_t3.o
w = f_t3.grn
bias = f_t3.alpha_unconstr_bias

#emu = h[locate,:] * torch.exp(-phi[locate,:]*(T.reshape((dim,1))-self.tau[locate,:])**2) + self.o[locate,:]
#rt = t*t_scale+t0
rt = torch.einsum('i,jk->ijk', t_sample.view(-1), t_scale) + t0

#if len(rt.shape) == 2:
    #rt = rt.reshape(1,-1)
#    rt = rt.unsqueeze(0)

### create new dimensions for parameters
phi = phi.expand(rt.shape[0], rt.shape[1],phi.shape[0], phi.shape[1])
o = o.expand(rt.shape[0], rt.shape[1],o.shape[0], o.shape[1])
h = h.expand(rt.shape[0], rt.shape[1],h.shape[0], h.shape[1])
tau = tau.expand(rt.shape[0], rt.shape[1],tau.shape[0], tau.shape[1])

emu = h * torch.exp(-phi*(rt.unsqueeze(3) - tau)**2) + o
#emu = h_rep * torch.exp(-phi_rep*(rt.unsqueeze(3) - tau_rep)**2) + o_rep

In [33]:
emu = h * torch.exp(-phi*(rt.unsqueeze(3) - tau)**2) + o

RuntimeError: MPS backend out of memory (MPS allocated: 14.64 GB, other allocations: 2.65 GB, max allowed: 18.13 GB). Tried to allocate 1.63 GB on private pool. Use PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0 to disable upper limit for memory allocations (may cause system failure).

In [35]:
torch.exp(f_t3.log_h)

tensor([[1.0000e+00, 6.5331e+03, 8.3326e+03,  ..., 1.0000e+00, 1.0000e+00,
         1.0000e+00],
        [1.0000e+00, 6.5331e+03, 1.0000e+00,  ..., 1.0000e+00, 1.0000e+00,
         1.0000e+00],
        [1.0000e+00, 6.5331e+03, 1.0000e+00,  ..., 1.0000e+00, 1.0000e+00,
         1.0000e+00],
        ...,
        [1.0000e+00, 1.0000e+00, 1.0000e+00,  ..., 1.0000e+00, 1.0000e+00,
         1.0000e+00],
        [1.0000e+00, 1.0000e+00, 1.0000e+00,  ..., 1.0000e+00, 1.0000e+00,
         1.0000e+00],
        [1.0000e+00, 1.0000e+00, 1.0000e+00,  ..., 1.0000e+00, 1.0000e+00,
         1.0000e+00]], device='mps:0', grad_fn=<ExpBackward0>)

In [49]:
phi = phi.to(mps_device)

In [50]:
phi = phi[None,None,:, :]

In [53]:
phi.expand(t.shape[0], t.shape[1],phi.shape[2], phi.shape[3])

tensor([[[[1.0000, 2.7183, 2.7183,  ..., 1.0000, 1.0000, 1.0000],
          [2.7183, 2.7183, 1.0000,  ..., 1.0000, 1.0000, 1.0000],
          [2.7183, 2.7183, 1.0000,  ..., 1.0000, 1.0000, 1.0000],
          ...,
          [1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000],
          [1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000],
          [1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000]],

         [[1.0000, 2.7183, 2.7183,  ..., 1.0000, 1.0000, 1.0000],
          [2.7183, 2.7183, 1.0000,  ..., 1.0000, 1.0000, 1.0000],
          [2.7183, 2.7183, 1.0000,  ..., 1.0000, 1.0000, 1.0000],
          ...,
          [1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000],
          [1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000],
          [1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000]],

         [[1.0000, 2.7183, 2.7183,  ..., 1.0000, 1.0000, 1.0000],
          [2.7183, 2.7183, 1.0000,  ..., 1.0000, 1.0000, 1.0000],
          [2.7183, 2.7183, 1.0000,  ..., 1

In [35]:
import datetime
starttime = datetime.datetime.now()
emu = h_rep * torch.exp(-phi_rep*(rt.unsqueeze(3) - tau_rep)**2) + o_rep

w_rep = w.repeat(rt.shape[0], rt.shape[1], 1, 1)
w_rep = w_rep.view(rt.shape[0], rt.shape[1], w.shape[0], w.shape[1])
emu = emu * w_rep

alpha_unconstr = emu.sum(dim=3)
#alpha_unconstr = alpha_unconstr + self.alpha_unconstr_bias[locate]
bias_rep = bias.repeat(rt.shape[0], rt.shape[1], 1)
alpha_unconstr = alpha_unconstr + bias_rep

## Generate transcription kinetic rate for time t
alpha = torch.clamp(alpha_unconstr,0,)
alpha = F.softsign(alpha)
endtime = datetime.datetime.now()
print(endtime - starttime)

0:00:00.009825


In [66]:
f_beta = lambda t: f_t3(t,t_scale,t0)*torch.exp(beta*((torch.einsum('i,jk->ijk', t.to(mps_device).view(-1), t_scale) + t0)))*t_scale

In [71]:
f_beta(torch.tensor(2))

tensor([[[2.4400e+05, 3.5495e+06, 1.8138e+07,  ..., 0.0000e+00,
          7.0994e+06, 5.6101e+08],
         [3.7764e+08, 2.2301e+13, 2.5238e+05,  ..., 0.0000e+00,
          1.8676e+12, 8.8445e+09],
         [8.6245e+11, 1.7863e+02, 6.5715e+10,  ..., 0.0000e+00,
          4.8630e+04, 4.8691e+12],
         ...,
         [1.4334e+01, 1.1040e+10, 3.6286e+12,  ..., 0.0000e+00,
          4.5279e+08, 1.1547e+09],
         [4.2046e+08, 2.0325e+06, 2.7620e+07,  ..., 0.0000e+00,
          9.9938e+14, 2.0619e+01],
         [1.4722e+07, 5.5826e+04, 5.8399e+02,  ..., 0.0000e+00,
          6.8258e+06, 8.2616e+00]]], device='mps:0', grad_fn=<MulBackward0>)

# Compare with torchode solver

In [38]:
class velocity_encoder(nn.Module):
    """ 
    encode the velocity
    time dependent transcription rate is determined by upstream emulator
    velocity could be build on top of this

    merge velocity encoder and emulator class
    """                 
    def __init__(
        self,
        n_int: int = 5,
        alpha_unconstr_init: torch.Tensor = None,
        W: torch.Tensor = (torch.FloatTensor(5, 5).uniform_() > 0.5).int(),
        W_int: torch.Tensor = None,
        log_h_int: torch.Tensor = None,
        global_time: bool = False,
    ):
        device = W.device
        super().__init__()
        self.n_int = n_int
        if global_time:
            self.log_h = torch.nn.Parameter(torch.randn(W.shape[1]))
            self.log_phi = torch.nn.Parameter(torch.randn(W.shape[1]))
            self.tau = torch.nn.Parameter(torch.randn(W.shape[1]))
            self.o = torch.nn.Parameter(torch.randn(W.shape[1]))
        else:
            self.log_h = torch.nn.Parameter(log_h_int.repeat(W.shape[0],1)*W)
            self.log_phi = torch.nn.Parameter(torch.ones(W.shape).to(device)*W)
            self.tau = torch.nn.Parameter(torch.ones(W.shape).to(device)*W*10)
            self.o = torch.nn.Parameter(torch.ones(W.shape).to(device)*W)

        self.mask_m = W
        self.global_time = global_time

        ## initialize grn
        self.grn = torch.nn.Parameter(W_int*self.mask_m)
        
        ## initilize gamma and beta
        self.beta_mean_unconstr = torch.nn.Parameter(0.5 * torch.ones(n_int))
        self.gamma_mean_unconstr = torch.nn.Parameter(-1 * torch.ones(n_int))
        self.alpha_unconstr_bias = torch.nn.Parameter(torch.zeros(n_int))
        self.alpha_unconstr_max = torch.nn.Parameter(torch.randn(n_int))
        # calculating emulating matrix
    
    ### define hook to froze the parameters
    def _set_mask_grad(self):
        self.hooks_grn = []
        if not self.global_time:
            self.hooks_log_h = []
            self.hooks_log_phi = []
            self.hooks_tau = []
            self.hooks_o = []
        #mask_m = self.mask_m
        
        def _hook_mask_no_regulator(grad):
            return grad * self.mask_m

        w_grn = self.grn.register_hook(_hook_mask_no_regulator)
        self.hooks_grn.append(w_grn)
        if not self.global_time:
            w_log_h = self.log_h.register_hook(_hook_mask_no_regulator)
            w_log_phi = self.log_phi.register_hook(_hook_mask_no_regulator)
            w_tau = self.tau.register_hook(_hook_mask_no_regulator)
            w_o = self.o.register_hook(_hook_mask_no_regulator)

            self.hooks_log_h.append(w_log_h)
            self.hooks_log_phi.append(w_log_phi)
            self.hooks_tau.append(w_tau)
            self.hooks_o.append(w_o)

    def emulator(t,log_h_v,log_phi_v,tau_v,o_v):
        pre = torch.exp(log_h_v)*torch.exp(-torch.exp(phi_v)*(t-tau_v)**2)+o_v
        
        return pre

    def emulation_all(self,t: torch.Tensor = None):
        if self.global_time:
            # broadcasting the time t
            t = t.repeat((self.mask_m.shape[0],1))

        emulate_m = torch.zeros([self.mask_m.shape[0], self.mask_m.shape[1], t.shape[1]])

        h = torch.exp(self.log_h)
        phi = torch.exp(self.log_phi)
        for i in range(t.shape[1]):
            # for each time stamps, predict the emulator predict value
            tt = t[:,i]
            emu = h * torch.exp(-phi*(tt.reshape((len(tt),1))-self.tau)**2) + self.o
            emulate_m[:,:,i] = emu

        return emulate_m


    def forward(self,t, y):
        ## split x into unspliced and spliced readout
        ## x is a matrix with (G*2), in which row is a subgraph (batch)
        #print(y)
        #assert torch.jit.isinstance(args, torch.Tensor)
        #assert torch.jit.isinstance(t, torch.Tensor)
        #assert torch.jit.isinstance(y, torch.Tensor)
        
        args = torch.arange(0, self.n_int).reshape((self.n_int,1))
        dim = args.shape[0]
        locate = args.ravel()
        if len(y.shape) == 1:
            u = y[0]
            s = y[1]
        else:  
            u = y[:,0]
            s = y[:,1]

        if self.global_time:
            u = u[locate]
            s = s[locate]
            ## when use global time, t is a single value
            T = t.repeat((dim,1))

            ## calculate emulator vector
            h = torch.exp(self.log_h)
            phi = torch.exp(self.log_phi)
            emu = h[locate,:] * torch.exp(-phi[locate,:]*(T.reshape((dim,1))-self.tau[locate,:])**2) + self.o[locate,:]
            
            ## Use the Emulator matrix to predict alpha
            emu = emu * self.grn[locate,:]
            alpha_unconstr = emu.sum(dim=1)
            alpha_unconstr = alpha_unconstr + self.alpha_unconstr[locate]
            
            ## Generate kinetic rate
            beta = torch.clamp(F.softplus(self.beta_mean_unconstr[locate]), 0, 50)
            gamma = torch.clamp(F.softplus(self.gamma_mean_unconstr[locate]), 0, 50)
            alpha = torch.clamp(F.softplus(alpha_unconstr),0,50)

            ## Predict velocity
            du = alpha - beta*u
            ds = beta*u - gamma*s

            du = du.reshape((dim,1))
            ds = ds.reshape((dim,1))

            v = torch.concatenate([du,ds],axis = 1)

        else:
            ## calculate emulator value
            ## t is a vector per gene (G*1)
            ## extract the corresponding gene
            #u = u[locate]
            #s = s[locate]
            #T = t[locate]

            ## Build Emulator matrix
            h = torch.exp(self.log_h)
            phi = torch.exp(self.log_phi)
            #emu = h[locate,:] * torch.exp(-phi[locate,:]*(T.reshape((dim,1))-self.tau[locate,:])**2) + self.o[locate,:]
            emu = h * torch.exp(-phi*(t.reshape((dim,1)) - self.tau)**2) + self.o

            ## Use the Emulator matrix to predict alpha
            #emu = emu * self.grn[locate,:]
            emu = emu * self.grn
            
            alpha_unconstr = emu.sum(dim=1)
            #alpha_unconstr = alpha_unconstr + self.alpha_unconstr_bias[locate]
            alpha_unconstr = alpha_unconstr + self.alpha_unconstr_bias

            ## Generate kinetic rate
            #beta = torch.clamp(F.softplus(self.beta_mean_unconstr[locate]), 0, 50)
            #gamma = torch.clamp(F.softplus(self.gamma_mean_unconstr[locate]), 0, 50)
            beta = torch.clamp(F.softplus(self.beta_mean_unconstr), 0, 50)
            gamma = torch.clamp(F.softplus(self.gamma_mean_unconstr), 0, 50)
            alpha = torch.clamp(alpha_unconstr,0,)
            alpha = F.softsign(alpha)*torch.clamp(F.softplus(self.alpha_unconstr_max), 0, 50)

            ## Predict velocity
            du = alpha - beta*u
            ds = beta*u - gamma*s
            
            du = du.reshape((dim,1))
            ds = ds.reshape((dim,1))

            v = torch.concatenate([du,ds],axis = 1)

        if len(y.shape) == 1:
            v = v.view(-1)

        return v

In [40]:
v_encoder = velocity_encoder(n_int = rgv_m.model.n_targets, alpha_unconstr_init = rgv_m.model.f_t.alpha_unconstr_bias,log_h_int = rgv_m.model.f_t.log_h[0,:],
                    W = W.T, W_int = rgv_m.model.f_t.grn)

In [41]:
T = t.T
t_eval, index_matrix = torch.sort(T, dim=1)

index2 = (t_eval[:,:-1] != t_eval[:,1:])
## estimate the shift value
subtraction_values,_ = torch.where((t_eval[:,1:] - t_eval[:,:-1])>0, (t_eval[:,1:] - t_eval[:,:-1]), torch.inf).min(axis=1)
## replace inf value = 0
subtraction_values[subtraction_values == float("Inf")] = 0

true_tensor = torch.ones((t_eval.shape[0],1), dtype=torch.bool)
index2 = torch.cat((index2, true_tensor.to(index2.device)),dim=1) ## index2 is used to get unique time points as odeint requires strictly increasing/decreasing time points

subtraction_values = subtraction_values[None, :].repeat(index2.shape[1], 1).T
t_eval[index2 == False] -= subtraction_values[index2 == False]*0.1

In [42]:
t_eval

tensor([[ 2.1117,  2.8942,  3.4313,  ..., 16.2034, 16.9352, 17.8356],
        [ 1.4085,  2.9288,  3.3572,  ..., 14.9389, 15.8927, 16.6538],
        [ 2.4939,  2.7330,  4.3067,  ..., 15.0287, 16.4146, 17.4256],
        ...,
        [ 1.1464,  3.7646,  5.2279,  ..., 16.8554, 16.9816, 17.1428],
        [ 1.9435,  4.4762,  4.6579,  ..., 16.6903, 17.2010, 17.5247],
        [ 1.7885,  2.8443,  3.9657,  ..., 14.3889, 14.9995, 16.9701]])

In [43]:
x0 = torch.zeros([250,2])
indices = torch.arange(0, x0.shape[0]).reshape((x0.shape[0],1))

In [44]:
import torchode as to
import datetime

starttime = datetime.datetime.now()

T = t.T
indices = torch.argsort(T, dim=1)
t_eval = torch.gather(T, dim = 1, index = indices)

index2 = (t_eval[:,:-1] != t_eval[:,1:])
## estimate the shift value
subtraction_values,_ = torch.where((t_eval[:,1:] - t_eval[:,:-1])>0, (t_eval[:,1:] - t_eval[:,:-1]), torch.inf).min(axis=1)
## replace inf value = 0
subtraction_values[subtraction_values == float("Inf")] = 0

true_tensor = torch.ones((t_eval.shape[0],1), dtype=torch.bool)
index2 = torch.cat((index2, true_tensor.to(index2.device)),dim=1) ## index2 is used to get unique time points as odeint requires strictly increasing/decreasing time points

subtraction_values = subtraction_values[None, :].repeat(index2.shape[1], 1).T
t_eval[index2 == False] -= subtraction_values[index2 == False]*0.1

term = to.ODETerm(v_encoder)
step_method = to.Dopri5(term=term)
step_size_controller = to.IntegralController(atol=1e-9, rtol=1e-6, term=term)
#step_size_controller = to.FixedStepController()
solver = to.AutoDiffAdjoint(step_method, step_size_controller)
#jit_solver = torch.jit.script(solver)
dt0 = torch.full((x0.shape[0],), 1)
sol = solver.solve(to.InitialValueProblem(y0=x0, t_eval=t_eval))

endtime = datetime.datetime.now()
print(endtime - starttime)

0:00:00.399154


In [45]:
T

tensor([[ 7.0304, 12.7919, 10.4655,  ..., 12.9181, 13.4688,  6.1694],
        [ 4.3107, 14.8696,  2.9288,  ..., 16.6538, 13.3592,  5.6252],
        [ 2.7330, 17.4256,  6.4632,  ..., 11.3390,  5.5270,  6.9934],
        ...,
        [ 7.8638,  6.2608, 11.8545,  ..., 10.7559, 16.3847, 16.8554],
        [ 8.7109, 16.5141,  6.6571,  ..., 13.8724, 15.6707, 10.7586],
        [ 2.8443, 12.8971, 10.0709,  ...,  8.4398,  7.6313, 11.7996]])

In [46]:
pre_u = torch.zeros_like(t_eval)
for i in range(t_eval.size(0)):
    pre_u[i][indices[i]] = sol.ys[:,:,0][i]
    
pre_s = torch.zeros_like(t_eval)
for i in range(t_eval.size(0)):
    pre_s[i][indices[i]] = sol.ys[:,:,1][i]

In [47]:
pre_u

tensor([[0.6583, 0.7938, 0.9838,  ..., 0.7788, 0.7310, 0.6510],
        [0.5976, 0.6515, 0.4908,  ..., 0.6381, 0.7063, 0.6248],
        [0.1320, 0.6367, 0.6219,  ..., 1.0028, 0.6021, 0.6273],
        ...,
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0757, 0.0758, 0.0749,  ..., 0.0775, 0.0760, 0.1088],
        [0.0755, 0.1242, 0.1583,  ..., 0.1174, 0.1172, 0.1367]],
       grad_fn=<CopySlices>)

In [48]:
pre_s

tensor([[1.4204, 2.5681, 2.2019,  ..., 2.5633, 2.5277, 1.2293],
        [0.8577, 2.3252, 0.3798,  ..., 2.1849, 2.4709, 1.2136],
        [0.0156, 2.1399, 1.1551,  ..., 2.3432, 0.8982, 1.2757],
        ...,
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.1939, 0.2451, 0.1573,  ..., 0.2554, 0.2478, 0.2422],
        [0.0404, 0.4000, 0.3402,  ..., 0.2988, 0.2798, 0.3995]],
       grad_fn=<CopySlices>)

In [74]:
u.T

tensor([[1.7287, 1.2348, 0.8037,  ..., 0.0000, 0.2128, 0.1554],
        [2.6200, 2.3405, 2.1547,  ..., 0.0000, 0.2467, 0.4071],
        [2.3092, 0.8660, 1.5925,  ..., 0.0000, 0.1924, 0.3574],
        ...,
        [2.6132, 2.1936, 2.4419,  ..., 0.0000, 0.2592, 0.3274],
        [2.5697, 2.4955, 1.4641,  ..., 0.0000, 0.2499, 0.3164],
        [1.6260, 1.4793, 1.6507,  ..., 0.0000, 0.2522, 0.4095]],
       grad_fn=<AddBackward0>)

In [92]:
s.shape

torch.Size([30, 250])

In [93]:
s2.shape

torch.Size([30, 250])

In [139]:
import scipy
corr = scipy.stats.spearmanr(u.cpu().detach().numpy(), u2.detach().numpy())
corr = np.diagonal(corr.statistic[0:250,250:(250*2)])

In [140]:
corr

array([0.99555061, 0.99955506, 0.99822024, 0.96440489, 0.91724138,
       0.78598443,        nan, 0.88565072, 0.99510567, 0.98353726,
       0.9105673 , 0.8407119 , 0.99822024, 0.89010011, 0.94660734,
       0.97285873, 0.79755284, 0.99866518,        nan,        nan,
              nan, 0.9919911 , 0.99911012, 0.90344828,        nan,
       0.98531702, 0.78998888, 0.97196885, 0.95951057, 0.92791991,
       0.86918799, 0.89187987, 0.99377086, 0.80155729, 0.96751947,
       0.95372636, 0.91679644, 0.95951057, 0.91457175, 0.90567297,
       0.85539488, 0.9919911 , 0.86073415, 0.97063404, 0.98175751,
       0.98042269, 0.9839822 , 0.91190211, 0.74549499, 0.90656285,
       0.92614016,        nan, 0.90478309, 0.9025584 , 0.90300334,
              nan, 0.7432703 , 0.96307008, 0.94126808, 0.96974416,
              nan,        nan,        nan,        nan,        nan,
       0.96395996, 0.90211346, 0.74060067,        nan, 0.98665184,
       0.99777531, 0.96751947, 0.7374861 , 0.96929922, 0.97953

In [174]:
tensor = torch.tensor([[3, 1, 4],
                       [5, 2, 1],
                       [0, 2, 6]])

# Create an index matrix that sorts each row of the tensor
sorted_indices = torch.argsort(T, dim=1)

# Use the sorted index matrix to sort each row of the tensor
sorted_tensor = torch.gather(T, 1, sorted_indices)

# Use the sorted index matrix to transform the sorted tensor back into the unsorted tensor
unsorted_tensor = torch.zeros_like(sorted_tensor)
for i in range(sorted_indices.size(0)):
    unsorted_tensor[i][sorted_indices[i]] = sorted_tensor[i]

# Print the original, sorted, and unsorted tensors
print("Original tensor:")
print(T)
print("Sorted tensor:")
print(sorted_tensor)
print("Unsorted tensor:")
print(unsorted_tensor)

Original tensor:
tensor([[10.1061, 10.0764, 12.3378,  ...,  6.5726,  5.6128, 13.1180],
        [13.0245,  9.9245, 10.4516,  ...,  7.7540,  9.4624, 13.4341],
        [ 7.4929, 10.2253,  4.3061,  ..., 14.6500,  4.2954,  4.8138],
        ...,
        [11.2416,  5.1236, 12.6985,  ..., 15.4801, 14.9228,  9.4909],
        [ 4.1051,  3.6933, 14.1141,  ...,  7.9020,  9.5526, 11.3433],
        [11.1905, 14.4320, 10.2723,  ...,  6.4391, 10.6447,  8.6281]])
Sorted tensor:
tensor([[ 1.2378,  3.1580,  3.3272,  ..., 16.2686, 16.5700, 16.9063],
        [ 1.3134,  1.9177,  3.2865,  ..., 17.4862, 17.6019, 18.3128],
        [ 0.5776,  3.6837,  4.2311,  ..., 15.2332, 16.0353, 17.9717],
        ...,
        [ 3.3419,  3.3658,  3.4432,  ..., 16.9976, 17.3424, 19.3139],
        [ 1.9450,  3.6933,  4.1051,  ..., 15.2883, 15.3973, 17.3052],
        [ 2.1951,  3.8047,  5.3273,  ..., 16.3272, 16.5309, 18.4443]])
Unsorted tensor:
tensor([[10.1061, 10.0764, 12.3378,  ...,  6.5726,  5.6128, 13.1180],
        [13.0

# test raw version

In [48]:
class alpha_encoder(nn.Module):
    """ 
    encode the time dependent alpha (f)
    time dependent transcription rate is determined by upstream emulator

    """                 
    def __init__(
        self,
        n_int: int = 5,
        alpha_unconstr_init: torch.Tensor = None,
        W: torch.Tensor = (torch.FloatTensor(5, 5).uniform_() > 0.5).int(),
        W_int: torch.Tensor = None,
        log_h_int: torch.Tensor = None,
        global_time: bool = False,
    ):
        device = W.device
        super().__init__()
        self.n_int = n_int
        if global_time:
            self.log_h = torch.nn.Parameter(torch.randn(W.shape[1]))
            self.log_phi = torch.nn.Parameter(torch.randn(W.shape[1]))
            self.tau = torch.nn.Parameter(torch.randn(W.shape[1]))
            self.o = torch.nn.Parameter(torch.randn(W.shape[1]))
        else:
            self.log_h = torch.nn.Parameter(log_h_int.repeat(W.shape[0],1)*W)
            self.log_phi = torch.nn.Parameter(torch.ones(W.shape).to(device)*W)
            self.tau = torch.nn.Parameter(torch.ones(W.shape).to(device)*W*10)
            self.o = torch.nn.Parameter(torch.ones(W.shape).to(device)*W)

        self.mask_m = W
        self.global_time = global_time

        ## initialize grn
        self.grn = torch.nn.Parameter(W_int*self.mask_m)
        
        ## initilize gamma and beta
        self.beta_mean_unconstr = torch.nn.Parameter(0.5 * torch.ones(n_int))
        self.gamma_mean_unconstr = torch.nn.Parameter(-1 * torch.ones(n_int))
        self.alpha_unconstr_bias = torch.nn.Parameter(torch.zeros(n_int))
        self.alpha_unconstr_max = torch.nn.Parameter(torch.randn(n_int))
        # calculating emulating matrix
    
    ### define hook to froze the parameters
    def _set_mask_grad(self):
        self.hooks_grn = []
        if not self.global_time:
            self.hooks_log_h = []
            self.hooks_log_phi = []
            self.hooks_tau = []
            self.hooks_o = []
        #mask_m = self.mask_m
        
        def _hook_mask_no_regulator(grad):
            return grad * self.mask_m

        w_grn = self.grn.register_hook(_hook_mask_no_regulator)
        self.hooks_grn.append(w_grn)
        if not self.global_time:
            w_log_h = self.log_h.register_hook(_hook_mask_no_regulator)
            w_log_phi = self.log_phi.register_hook(_hook_mask_no_regulator)
            w_tau = self.tau.register_hook(_hook_mask_no_regulator)
            w_o = self.o.register_hook(_hook_mask_no_regulator)

            self.hooks_log_h.append(w_log_h)
            self.hooks_log_phi.append(w_log_phi)
            self.hooks_tau.append(w_tau)
            self.hooks_o.append(w_o)

    def emulator(t,log_h_v,log_phi_v,tau_v,o_v):
        pre = torch.exp(log_h_v)*torch.exp(-torch.exp(phi_v)*(t-tau_v)**2)+o_v
        
        return pre

    def emulation_all(self,t: torch.Tensor = None):
        if self.global_time:
            # broadcasting the time t
            t = t.repeat((self.mask_m.shape[0],1))

        emulate_m = torch.zeros([self.mask_m.shape[0], self.mask_m.shape[1], t.shape[1]])

        h = torch.exp(self.log_h)
        phi = torch.exp(self.log_phi)
        for i in range(t.shape[1]):
            # for each time stamps, predict the emulator predict value
            tt = t[:,i]
            emu = h * torch.exp(-phi*(tt.reshape((len(tt),1))-self.tau)**2) + self.o
            emulate_m[:,:,i] = emu

        return emulate_m


    def forward(self,t,g):
        ## Encode 

        if self.global_time:
            u = u[locate]
            s = s[locate]
            ## when use global time, t is a single value
            T = t.repeat((dim,1))

            ## calculate emulator vector
            h = torch.exp(self.log_h)
            phi = torch.exp(self.log_phi)
            emu = h[locate,:] * torch.exp(-phi[locate,:]*(T.reshape((dim,1))-self.tau[locate,:])**2) + self.o[locate,:]
            
            ## Use the Emulator matrix to predict alpha
            emu = emu * self.grn[locate,:]
            alpha_unconstr = emu.sum(dim=1)
            alpha_unconstr = alpha_unconstr + self.alpha_unconstr[locate]
            
            ## Generate kinetic rate
            beta = torch.clamp(F.softplus(self.beta_mean_unconstr[locate]), 0, 50)
            gamma = torch.clamp(F.softplus(self.gamma_mean_unconstr[locate]), 0, 50)
            alpha = torch.clamp(F.softplus(alpha_unconstr),0,50)

            ## Predict velocity
            du = alpha - beta*u
            ds = beta*u - gamma*s

            du = du.reshape((dim,1))
            ds = ds.reshape((dim,1))

            v = torch.concatenate([du,ds],axis = 1)

        else:
            ## calculate emulator value
            ## output the f_g(t)
            
            ## Build Emulator matrix for gene g
            h = torch.exp(self.log_h)[g,:].view(-1)
            phi = torch.exp(self.log_phi)[g,:].view(-1)
            tau = self.tau[g,:].view(-1)
            o = self.o[g,:].view(-1)
            w = self.grn[g,:].view(-1)
            bias = self.alpha_unconstr_bias[g]

            #emu = h[locate,:] * torch.exp(-phi[locate,:]*(T.reshape((dim,1))-self.tau[locate,:])**2) + self.o[locate,:]
            if len(t.shape) > 1:
                alpha_all = []
                for i in range(t.shape[0]):
                    t_x = t[i]
                    emu = h * torch.exp(-phi*(t_x - tau)**2) + o

                    ## Use the Emulator matrix to predict alpha
                    #emu = emu * self.grn[locate,:]
                    emu = emu * w

                    alpha_unconstr = emu.sum()
                    #alpha_unconstr = alpha_unconstr + self.alpha_unconstr_bias[locate]
                    alpha_unconstr = alpha_unconstr + bias

                    ## Generate transcription kinetic rate for time t
                    alpha = torch.clamp(alpha_unconstr,0,)
                    alpha = F.softsign(alpha)
                    alpha_all.append(alpha)
                    
                alpha = torch.tensor(alpha_all)
            else:
                emu = h * torch.exp(-phi*(t - tau)**2) + o

                ## Use the Emulator matrix to predict alpha
                #emu = emu * self.grn[locate,:]
                emu = emu * w

                alpha_unconstr = emu.sum()
                #alpha_unconstr = alpha_unconstr + self.alpha_unconstr_bias[locate]
                alpha_unconstr = alpha_unconstr + bias

                ## Generate transcription kinetic rate for time t
                alpha = torch.clamp(alpha_unconstr,0,)
                alpha = F.softsign(alpha)

        return alpha
    
def SolveInitialValueProblem(f_t, x0, t0, t_eval):
    
    ## generate the prediction of unspliced/spliced readout at time t for every gene
    ## use torchquad integral, different with torchode, the t_eval no longer need to be ordered
    
    ## get the kinetic parameters
    beta = torch.clamp(F.softplus(f_t.beta_mean_unconstr), 0, 50)
    gamma = torch.clamp(F.softplus(f_t.gamma_mean_unconstr), 0, 50)
    alpha_max = torch.clamp(F.softplus(f_t.alpha_unconstr_max),0,50)

    ## define integral function
    def integral_alpha_beta(f_t, tt, t0, beta, g):
        f_i = lambda t: f_t(t,g)*torch.exp(beta[g]*t.view(-1))
        integration_domain = [[t0[g],tt]]
        result = simp.integrate(f_i, dim=1, N=101, integration_domain=integration_domain)
        return result
        
    def integral_alpha_gamma(f_t, tt,t0, gamma, g):
        f_i = lambda t: f_t(t,g)*torch.exp(gamma[g]*t.view(-1))
        integration_domain = [[t0[g],tt]]
        result = simp.integrate(f_i, dim=1, N=101, integration_domain=integration_domain)
        return result

    ## get the initial condition (i.e. u,s = 0,0)
    u0 = x0[:,0].view(-1)
    s0 = x0[:,1].view(-1)
    pre_u = torch.zeros(t_eval.shape)
    pre_s = torch.zeros(t_eval.shape)
    
    ## build for loop to generate readout for each targets
    for g, t in enumerate(t_eval):
        u0g = u0[g]
        s0g = s0[g]
        
        ## calculate integral for gene g
        integral_tensor_alpha_beta = torch.tensor(list(map(lambda tt: integral_alpha_beta(tt=tt,f_t=f_t,t0=t0,beta = beta,g = g), t)))
        integral_tensor_alpha_gamma = torch.tensor(list(map(lambda tt: integral_alpha_gamma(tt=tt,f_t=f_t,t0=t0,gamma = gamma,g = g), t)))
        
        #ug = u0g*torch.exp(-beta[g]*t) + alpha_max[g]*torch.exp(-beta[g]*t)*integral_tensor_alpha_beta
        #sg = s0g*torch.exp(-gamma[g]*t) + \
        #    ( (alpha_max[g]*beta[g])/(gamma[g] - beta[g]) )*(torch.exp(-beta[g]*t)*integral_tensor_alpha_beta - torch.exp(-gamma[g]*t)*integral_tensor_alpha_gamma) + \
        #    ( (beta[g]*u0g)/(gamma[g] - beta[g]) )*(torch.exp(-beta[g]*t) - torch.exp(-gamma[g]*t))
        
        pre_u[g,:] = integral_tensor_alpha_beta
        pre_s[g,:] = integral_tensor_alpha_gamma
        #print(g)
    return pre_u, pre_s

In [49]:
f_t = alpha_encoder(n_int = rgv_m.model.n_targets, alpha_unconstr_init = rgv_m.model.v_encoder.alpha_unconstr_bias,log_h_int = rgv_m.model.v_encoder.log_h[0,:],
                    W = W.T, W_int = rgv_m.model.v_encoder.grn)

In [50]:
t

tensor([[ 7.0304,  4.3107,  2.7330,  ...,  7.8638,  8.7109,  2.8443],
        [12.7919, 14.8696, 17.4256,  ...,  6.2608, 16.5141, 12.8971],
        [10.4655,  2.9288,  6.4632,  ..., 11.8545,  6.6571, 10.0709],
        ...,
        [11.4710, 10.4500,  6.0351,  ..., 11.6317,  9.8647, 12.9834],
        [ 4.1471,  6.8124, 16.2744,  ...,  7.4569,  6.7320,  7.3953],
        [11.0352, 13.1345,  5.0188,  ..., 13.9301,  6.2952,  9.8744]])

In [46]:
def integral_alpha_beta(f_t, tt, t0, beta, g):
    f_i = lambda tx: f_t(tx,g)*torch.exp(beta[g]*tx.view(-1))
    integration_domain = [[t0[g],tt]]
    result = simp.integrate(f_i, dim=1, N=101, integration_domain=integration_domain)
    return result

val = []
val2 = []
for i in range(250):
    val.append(integral_alpha_beta(tt=t[0,:][i],f_t=f_t,t0=t0,beta = beta,g = i))
    val2.append(f_t(t=t[0,:][i],g = i))

print(torch.tensor(val2))
print(torch.tensor(val))

tensor([0.6466, 0.6188, 0.6188, 0.5963, 0.6424, 0.7336, 0.0000, 0.2757, 0.2469,
        0.2423, 0.7792, 0.6513, 0.6605, 0.7462, 0.6503, 0.6628, 0.7865, 0.6536,
        0.0000, 0.0000, 0.0000, 0.1511, 0.1516, 0.6611, 0.0000, 0.5174, 0.5219,
        0.2701, 0.3650, 0.5344, 0.2397, 0.6621, 0.6678, 0.7116, 0.4560, 0.4577,
        0.4551, 0.4865, 0.6590, 0.6602, 0.6613, 0.5605, 0.5485, 0.4566, 0.5268,
        0.4721, 0.5381, 0.6570, 0.5523, 0.4723, 0.5593, 0.0000, 0.6158, 0.5800,
        0.5940, 0.0000, 0.6470, 0.3482, 0.3598, 0.5011, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.7044, 0.6917, 0.4901, 0.0000, 0.5312, 0.5418, 0.5365,
        0.5241, 0.6061, 0.6151, 0.5175, 0.6175, 0.3918, 0.6821, 0.5146, 0.5236,
        0.0000, 0.6974, 0.7034, 0.6863, 0.6519, 0.6617, 0.7456, 0.6605, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.4037, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.6621, 0.6624, 0.6701,
        0.6624, 0.6589, 0.6614, 0.0000, 

In [199]:
def integral_operator(tt,f_t, t0, beta, gamma):
    t_scale = tt - t0 # when t0 is non-zero, minus t0 to make sure time start from 0
    f_beta = lambda t: f_t(t,t_scale,t0)*t_scale
    f_gamma = lambda t: f_t(t,t_scale,t0)*torch.exp(gamma*(t_scale*t+t0)*0)
    integration_domain = [[0,1]]
    int_beta = simp.integrate(f_beta, dim=1, N=101, integration_domain=integration_domain)
    int_gamma = simp.integrate(f_gamma, dim=1, N=101, integration_domain=integration_domain)
    return int_beta

print(f_t2(1,t[0,:],t0))

starttime = datetime.datetime.now()
integral_operator(tt=t[0,:],f_t=f_t2,t0=t0,beta = beta, gamma = gamma)

tensor([[0.9999, 0.6188, 0.6188, 0.5963, 0.6424, 0.5937, 0.0000, 0.3205, 0.2336,
         0.2794, 0.6613, 0.6513, 0.6587, 0.6592, 0.7878, 0.6757, 0.6487, 0.6536,
         0.0000, 0.0000, 0.0000, 0.1511, 0.2522, 0.6611, 0.0000, 0.5082, 0.5250,
         0.2819, 0.2478, 0.5365, 0.2397, 0.6621, 0.6570, 0.6544, 0.4560, 0.4619,
         0.4570, 0.4690, 0.6590, 0.6602, 0.6613, 0.5605, 0.6292, 0.4057, 0.5273,
         0.4721, 0.5381, 0.5297, 0.5883, 0.4780, 0.5593, 0.0000, 0.5928, 0.5800,
         0.5940, 0.0000, 0.6476, 0.5144, 0.3598, 0.5014, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.6949, 0.6917, 0.4901, 0.0000, 0.5312, 0.5094, 0.5365,
         0.5242, 0.6082, 0.6151, 0.5175, 0.6175, 0.3918, 0.6821, 0.5146, 0.5236,
         0.0000, 0.6974, 0.8043, 0.6864, 0.6519, 0.6617, 0.7456, 0.6605, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.4037, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.7406, 0.6624, 0.6619,
         0.6624, 0.6589, 0.6

In [179]:
g = 2
t = t_real[10,:][2]
h = torch.exp(f_t.log_h)[g,:].view(-1)
phi = torch.exp(f_t.log_phi)[g,:].view(-1)
tau = f_t.tau[g,:].view(-1)
o = f_t.o[g,:].view(-1)
w = f_t.grn[g,:].view(-1)
bias = f_t.alpha_unconstr_bias[g]

#emu = h[locate,:] * torch.exp(-phi[locate,:]*(T.reshape((dim,1))-self.tau[locate,:])**2) + self.o[locate,:]
emu = h * torch.exp(-phi*(t - tau)**2) + o
print(emu)
## Use the Emulator matrix to predict alpha
#emu = emu * self.grn[locate,:]
#emu = emu * w

#alpha_unconstr = emu.sum()
#alpha_unconstr = alpha_unconstr + self.alpha_unconstr_bias[locate]
#alpha_unconstr = alpha_unconstr + bias

## Generate transcription kinetic rate for time t
#alpha = torch.clamp(alpha_unconstr,0,)
#alpha = F.softsign(alpha)
#alpha

tensor([1.1988e+00, 1.3001e+03, 1.0186e-37, 1.0186e-37, 1.0186e-37, 1.0186e-37,
        1.0186e-37, 1.0186e-37, 1.0186e-37, 1.0186e-37, 1.0186e-37, 1.0186e-37,
        1.0186e-37, 1.0186e-37, 1.0186e-37, 1.0186e-37, 1.0186e-37, 1.0186e-37,
        1.0186e-37, 1.0186e-37, 1.0186e-37, 1.0186e-37, 1.0186e-37, 1.0186e-37,
        1.0186e-37, 1.0186e-37, 1.0186e-37, 1.0186e-37, 1.0186e-37, 1.0186e-37,
        1.0186e-37, 1.0186e-37, 1.0186e-37, 1.0186e-37, 1.0186e-37, 1.0186e-37,
        1.0186e-37, 1.0186e-37, 1.0186e-37, 1.0186e-37, 1.0186e-37, 1.0186e-37,
        1.0186e-37, 1.0186e-37, 1.0186e-37, 1.0186e-37, 1.0186e-37, 1.0186e-37,
        1.0186e-37, 1.0186e-37, 1.0186e-37, 1.0186e-37, 1.0186e-37, 1.0186e-37,
        1.0186e-37, 1.0186e-37, 1.0186e-37, 1.0186e-37, 1.0186e-37, 1.0186e-37,
        1.0186e-37, 1.0186e-37, 1.0186e-37, 1.0186e-37, 1.0186e-37, 1.0186e-37,
        1.0186e-37, 1.0186e-37, 1.0186e-37, 1.0186e-37, 1.0186e-37, 1.0186e-37,
        1.0186e-37, 1.0186e-37, 1.0186e-

In [171]:
h

tensor([1.0000e+00, 6.5331e+03, 1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00,
        1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00,
        1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00,
        1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00,
        1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00,
        1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00,
        1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00,
        1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00,
        1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00,
        1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00,
        1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00,
        1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00,
        1.0000e+00, 1.0000e+00, 1.0000e+

In [176]:
phi

tensor([2.7183, 2.7183, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 

In [177]:
tau

tensor([10., 10.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.], grad_fn=<ViewBackward0>)

In [178]:
o

tensor([1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.], grad_fn=<ViewBackward0>)

In [167]:
t_scale = t_real[10,:]
t = 1
h = torch.exp(f_t.log_h)
phi = torch.exp(f_t.log_phi)
tau = f_t.tau
o = f_t.o
w = f_t.grn
bias = f_t.alpha_unconstr_bias

#emu = h[locate,:] * torch.exp(-phi[locate,:]*(T.reshape((dim,1))-self.tau[locate,:])**2) + self.o[locate,:]
rt = t*t_scale+t0
if len(rt.shape) == 1:
    rt = rt.reshape(1,-1)

### create new dimensions for parameters
phi_rep = phi.repeat(rt.shape[0], 1, 1)
phi_rep = phi_rep.view(rt.shape[0], phi.shape[0], phi.shape[1])

o_rep = o.repeat(rt.shape[0], 1, 1)
o_rep = o_rep.view(rt.shape[0], o.shape[0], o.shape[1])

h_rep = h.repeat(rt.shape[0], 1, 1)
h_rep = h_rep.view(rt.shape[0], h.shape[0], h.shape[1])

tau_rep = tau.repeat(rt.shape[0], 1, 1)
tau_rep = tau_rep.view(rt.shape[0], tau.shape[0], tau.shape[1])

emu = h_rep[0,2,:] * torch.exp(-phi_rep[0,2,:]*(rt.unsqueeze(2)[0,2,0] - tau_rep[0,2,:])**2) + o_rep[0,2,:]
print(emu)
## Use the Emulator matrix to predict alpha
#emu = emu * self.grn[locate,:]

#w_rep = w.repeat(rt.shape[0], 1, 1)
#w_rep = w_rep.view(rt.shape[0], w.shape[0], w.shape[1])
#emu = emu * w_rep

#alpha_unconstr = emu.sum(dim=2)
#alpha_unconstr = alpha_unconstr + self.alpha_unconstr_bias[locate]
#bias_rep = bias.repeat(rt.shape[0], 1)
#alpha_unconstr = alpha_unconstr + bias_rep

## Generate transcription kinetic rate for time t
#alpha = torch.clamp(alpha_unconstr,0,)
#alpha = F.softsign(alpha)
#alpha

tensor([1.1988e+00, 1.3001e+03, 1.0186e-37, 1.0186e-37, 1.0186e-37, 1.0186e-37,
        1.0186e-37, 1.0186e-37, 1.0186e-37, 1.0186e-37, 1.0186e-37, 1.0186e-37,
        1.0186e-37, 1.0186e-37, 1.0186e-37, 1.0186e-37, 1.0186e-37, 1.0186e-37,
        1.0186e-37, 1.0186e-37, 1.0186e-37, 1.0186e-37, 1.0186e-37, 1.0186e-37,
        1.0186e-37, 1.0186e-37, 1.0186e-37, 1.0186e-37, 1.0186e-37, 1.0186e-37,
        1.0186e-37, 1.0186e-37, 1.0186e-37, 1.0186e-37, 1.0186e-37, 1.0186e-37,
        1.0186e-37, 1.0186e-37, 1.0186e-37, 1.0186e-37, 1.0186e-37, 1.0186e-37,
        1.0186e-37, 1.0186e-37, 1.0186e-37, 1.0186e-37, 1.0186e-37, 1.0186e-37,
        1.0186e-37, 1.0186e-37, 1.0186e-37, 1.0186e-37, 1.0186e-37, 1.0186e-37,
        1.0186e-37, 1.0186e-37, 1.0186e-37, 1.0186e-37, 1.0186e-37, 1.0186e-37,
        1.0186e-37, 1.0186e-37, 1.0186e-37, 1.0186e-37, 1.0186e-37, 1.0186e-37,
        1.0186e-37, 1.0186e-37, 1.0186e-37, 1.0186e-37, 1.0186e-37, 1.0186e-37,
        1.0186e-37, 1.0186e-37, 1.0186e-

In [168]:
h_rep[0,2,:]

tensor([1.0000e+00, 6.5331e+03, 1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00,
        1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00,
        1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00,
        1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00,
        1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00,
        1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00,
        1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00,
        1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00,
        1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00,
        1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00,
        1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00,
        1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00,
        1.0000e+00, 1.0000e+00, 1.0000e+

In [172]:
phi_rep[0,2,:]

tensor([2.7183, 2.7183, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 

In [173]:
rt.unsqueeze(2)[0,2,0]

tensor(9.2291)

In [174]:
tau_rep[0,2,:]

tensor([10., 10.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.], grad_fn=<SliceBackward0>)

In [161]:
o_rep[0,2,:]

tensor([1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.], grad_fn=<SliceBackward0>)

In [60]:
starttime = datetime.datetime.now()
a,b = SolveInitialValueProblem(f_t = f_t, x0 = x0,t0 = t0, t_eval = t.T)
endtime = datetime.datetime.now()
print(endtime - starttime)

0:03:10.756549


In [198]:
b

tensor([[ 16.6076, 141.4018,  67.6779,   4.9476, 217.0428,  12.0619, 358.3701,
           3.0464, 195.6053, 172.0990,   9.8396,   8.4261,   7.4889,  25.2139,
          20.1298, 114.5480,  19.2105,   3.9829, 154.5477,  40.7347, 578.9570,
         443.5404, 209.8475, 112.5899, 317.2336,  65.3547,   1.9354, 145.9795,
         168.2146,  12.1935, 356.7754,   1.1908, 145.6228,   7.9605, 474.8371,
           8.3131,  20.0553,  19.8439,  50.9583, 176.2853,  32.9334, 358.9092,
         191.8283,   6.7982, 202.5353,  29.9600,  22.3159,   3.8278,  27.7432,
          10.4419, 180.6682,   4.1057, 128.3981,   9.7866,  18.9930,  16.2818,
           6.1908,  47.5848, 392.1898,  17.0861, 599.2476,  50.0054,  25.7103,
         340.9219,   1.9223, 166.9864,   7.6977,  17.3980, 519.7316,  67.2864,
           4.4295,   3.8262,  74.7777, 278.2805,  16.4839,  73.1085,  24.7631,
          78.2489,   7.1848,  31.0928,  51.3320,  45.4606,   3.4379,  25.2979,
          17.0837, 167.1650,  63.4664, 295.2383,  15

In [45]:
def integral_alpha_beta(f_t, tt, t0, beta, g):
    f_i = lambda t: f_t(t,g)*torch.exp(beta[g]*t)
    integration_domain = [[t0[g],tt]]
    result = simp.integrate(f_i, dim=1, N=101, integration_domain=integration_domain)
    return result

In [66]:
tt2 = t[:,0]
integral_tensor_alpha_beta = torch.tensor(list(map(lambda tt: integral_alpha_beta(tt=tt,f_t=f_t,t0=t0,beta = beta,g = 1), tt2)))

In [67]:
integral_tensor_alpha_beta 

tensor([5.8144e+00, 3.1680e+03, 7.1853e+00, 1.0543e+07, 6.1589e+03, 2.3187e+01,
        1.5655e+03, 1.6132e+02, 8.6527e+04, 1.1143e+07, 9.9307e+03, 1.7259e+04,
        1.7334e+06, 1.5068e+06, 7.7024e+01, 2.6948e+01, 3.8685e+00, 2.6380e+06,
        1.5074e+04, 1.8439e+05, 1.9408e+03, 4.8340e+00, 6.9157e+02, 6.6871e+05,
        6.8449e+01, 1.5221e+02, 6.0650e+05, 5.6958e+03, 2.8019e+03, 3.6626e+06,
        9.1829e+05, 1.1096e+04, 1.4705e+07, 9.4920e+03, 2.8942e+01, 3.5842e+06,
        6.8350e+01, 1.2146e+03, 5.6564e+07, 3.8825e+04, 1.9531e+04, 8.0093e+01,
        4.5085e+02, 1.2060e+07, 5.0763e+03, 4.2380e+05, 8.6835e+02, 2.5860e+02,
        7.4527e+02, 4.5351e+06, 5.4080e+03, 1.3778e+05, 3.4884e+05, 5.3770e+04,
        4.2732e+05, 1.0718e+01, 4.5153e+02, 9.7291e+05, 6.6496e+02, 4.0661e+04,
        2.9465e+03, 1.4752e+07, 2.8987e+05, 5.1078e+02, 2.8592e+04, 3.7677e+07,
        2.0604e+02, 3.6338e+05, 1.1322e+01, 2.4162e+05, 6.7300e+03, 1.4739e+05,
        5.9985e+01, 7.4261e+04, 4.8347e+

In [65]:
a

tensor([[5.8184e+00, 3.1705e+03, 7.1902e+00,  ..., 2.7992e+05, 3.2672e+07,
         5.6466e+00],
        [2.3353e+07, 1.7111e+04, 1.2919e+04,  ..., 3.9792e+02, 1.5302e+05,
         2.1643e+01],
        [2.2204e+05, 7.0898e+06, 3.0740e+07,  ..., 7.5634e+03, 4.7903e+06,
         2.3315e+01],
        ...,
        [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        [3.3748e+02, 1.2055e+05, 5.8347e+05,  ..., 1.6824e+06, 7.3759e+06,
         1.6380e+05],
        [6.6162e+01, 1.8053e+06, 1.5742e+06,  ..., 2.7177e+02, 1.7108e+01,
         1.3802e+05]])